# Generated by Django 5.2 on 2025-04-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='1163516985', editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa y accesorios'), ('hogar', 'Hogar y muebles'), ('juguetes', 'Juguetes y hobbies'), ('herramientas', 'Herramientas y construcción'), ('vehiculos', 'Vehículos y repuestos'), ('arte', 'Arte y coleccionables'), ('libros', 'Libros y papelería'), ('deportes', 'Deportes y aire libre'), ('otros', 'Otros')], max_length=30)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Cerrado', 'Cerrado')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
