# Generated by Django 5.2 on 2025-04-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10, null=True),
        ),
    ]
