# Generated by Django 5.2 on 2025-04-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(default='A129CAD594', editable=False, max_length=10, unique=True),
        ),
    ]
