# Generated by Django 5.2 on 2025-04-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(default='23314F323F', editable=False, max_length=10, unique=True),
        ),
    ]
