# Generated by Django 5.2 on 2025-04-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(default='19C0D32637', editable=False, max_length=10, unique=True),
        ),
    ]
