# Generated by Django 5.2 on 2025-04-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_item_image1_alter_item_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa y accesorios'), ('hogar', 'Hogar y muebles'), ('juguetes', 'Juguetes y hobbies'), ('herramientas', 'Herramientas y construcción'), ('vehiculos', 'Vehículos y repuestos'), ('arte', 'Arte y coleccionables'), ('libros', 'Libros y papelería'), ('deportes', 'Deportes y aire libre'), ('otros', 'Otros')], max_length=30),
        ),
    ]
