# Generated by Django 5.2 on 2025-05-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(default='42E9965DE1', editable=False, max_length=10, unique=True),
        ),
    ]
