# Generated by Django 5.2 on 2025-04-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cerrado', 'Cerrado')], default='Activo', max_length=10),
        ),
    ]
