# Generated by Django 5.2 on 2025-05-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(default='8A18264DEB', editable=False, max_length=10, unique=True),
        ),
    ]
